apiVersion: v1
kind: Service
metadata:
{{- if (.Values.service.subdomain) or (.Values.service.annotations) }}
  annotations:
{{- if .Values.service.subdomain }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Release.Name }}.{{ .Values.service.subdomain }}.landinsight.io
{{- end }}
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
{{- end }}
  name: {{ template "helm.fullname" . }}
  labels:
    app: {{ template "helm.name" . }}
    chart: {{ template "helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "helm.name" . }}
    release: {{ .Release.Name }}
    role: ml-server
  externalTrafficPolicy: Local
{{- if .Values.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.loadBalancerSourceRanges | indent 4 }}
{{- end }}
