maxPodReplicaCount: 20

service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: "sg-0d69fa71"
  subdomain: k8-prod

s3:
  bucket: landtech-ml-models
  prefix: landtech_policy_tagging

resources:
  requests:
    memory: "3500Mi"
    cpu: "1800m"