service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: "sg-73a11e0f"
  subdomain: k8-staging

resources:
  requests:
    memory: "1000Mi"
    cpu: "400m"

podDisruptionBudget: |
  minAvailable: 1

minPodReplicaCount: 1