# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

maxPodReplicaCount: 10
minPodReplicaCount: 1

image:
  repository: landtech-policy-tagging
  tag: local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

model:
  path: /models
  name: landtech_policy_tagging

s3:
  bucket: landtech-ml-models-staging
  prefix: landtech_policy_tagging

volumeMountPath: /models

targetAverageUtilization: 80

# Check for new models every five seconds
modelsPollSleepDuration: 5

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

tolerations: []

affinity: {}

# Run setup_local.sh once minikube is running to set this up
volumes:
  - name: models-storage
    hostPath:
      path: /models
      type: DirectoryOrCreate

